# Generated by Django 4.1.7 on 2023-04-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_indbox"),
    ]

    operations = [
        migrations.RemoveField(model_name="indbox", name="by",),
        migrations.RemoveField(model_name="indbox", name="to",),
        migrations.RemoveField(model_name="students", name="department",),
        migrations.DeleteModel(name="Attendence",),
        migrations.DeleteModel(name="Indbox",),
        migrations.DeleteModel(name="Students",),
    ]
