# Generated by Django 4.1.7 on 2023-04-01 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_standard_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="standard",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kasha",
                to="core.standard",
            ),
        ),
    ]
