# Generated by Django 4.1.7 on 2023-04-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_subjects_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("upload", models.ImageField(upload_to="")),
            ],
        ),
    ]
